# mchoi John M Choi #
CC = gcc
CFLAGS = -Wall -g -std=c99

ALL: prob_3_1 prob_3_2
prob_3_1:
	$(CC) $(CFLAGS) prob_3_1.c -o prob_3_1 -lpthread
prob_3_2:
	$(CC) $(CFLAGS) prob_3_2.c -o prob_3_2 -lpthread

clean:
	rm -rf *.o
	rm -f prob_3_1
	rm -f prob_3_2
