# mchoi John M Choi #

CC = gcc
CFLAGS = -Wall -std=c99 -g -pthread

ALL: prob_3
prob_3: prob_3.c
	$(CC) $(CFLAGS) prob_3.c -o prob_3
prob_1:
	$(CC) prob_1.c -o prob_1 -g

clean:
	rm -f *.o
	rm -f prob_3
	rm -f prob_1
